name: 'Ghost Markdown Backup'
description: 'Automatically backs up posts from a Ghost instance to markdown through the Ghost content API'
author: 'animafps'
inputs:
  url:
    description: 'URL of the Ghost API'
    required: true
  key:
    description: 'Ghost API key'
    required: true
  version:
    description: 'API version'
    required: false
    default: 'v4'
runs:
  using: 'node12'
  main: 'dist/index.js'
